name: Electron Build

on:
  push:
    branches:
      - "**"

jobs:
  build-hive:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ['iris', 'hive']
    steps:
      - name: Cloning Repository
        uses: actions/checkout@v3
      - name: Building frontend
        run: |
          touch ${{matrix.environment}}
          mkdir dir
          touch dir/test
      - name: Create Archive
        run: |
          cd ../
          zip -r ${{matrix.environment}}-notification.zip action -x ".git/*" ".github/*"
          ls -la
      - uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.environment}}-notification
          path: ${{matrix.environment}}-notification.zip
