name: Electron Build

on:
  push:
    branches:
      - "**"

jobs:
  build-hive:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ['iris', 'hive']
    steps:
      - name: Cloning Repository
        uses: actions/checkout@v3
      - name: Building frontend
        run: |
          touch ${{matrix.environment}}
          mkdir dir
          touch dir/test
      - name: Create Archive
        run: |
          cd ../
          zip -r ${{matrix.environment}}-notification.zip action -x ".git/*" ".github/*"
          ls -la
          mv ${{matrix.environment}}-notification.zip action/
      - uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.environment}}-notification
          path: ${{matrix.environment}}-notification.zip
  publish:
    permissions:
      contents: write
      actions: write
    needs:
      - build-hive
    runs-on: ubuntu-latest
    steps:
      - name: Download MacOS ARM64 Iris
        uses: actions/download-artifact@v4
        with:
          name: iris-notification
          path: artifacts/
      - name: Download MacOS ARM64 Hive
        uses: actions/download-artifact@v4
        with:
          name: hive-notification
          path: artifacts/
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/*-notification.zip
